name = 'Typo'
license = 'MIT'
licenselink = 'https://github.com/tomfran/typo/blob/main/LICENSE'
description = 'A simple Hugo theme'

homepage = 'https://github.com/tomfran/typo'

demosite = 'https://tomfran.github.io/'

tags = ["responsive", "simple", "clean", "light", "dark", "blog", "minimal"]

features = [
    "responsive",
    "blog",
    "table-of-contents",
    "highlight.js",
    "favicon",
    "social-icons",
    "minified-assets",
    "dark-light-images",
]

[author]
name = 'Francesco Tomaselli'
homepage = 'https://tomfran.github.io/'
